#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/klyshko.
#
# SPDX-License-Identifier: Apache-2.0
#

FROM ghcr.io/carbynestack/spdz:5350e66

ARG UBUNTU_CODENAME=focal

ARG RELEASE_PAGE="https://github.com/carbynestack/klyshko/releases"

# Install dependencies and Gramine + Intel SGX packages
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y curl gnupg2 binutils

RUN curl -fsSLo /usr/share/keyrings/gramine-keyring.gpg https://packages.gramineproject.io/gramine-keyring.gpg && \
    echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/gramine-keyring.gpg] https://packages.gramineproject.io/ '${UBUNTU_CODENAME}' main' > /etc/apt/sources.list.d/gramine.list

RUN curl -fsSLo /usr/share/keyrings/intel-sgx-deb.key https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key && \
    echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/intel-sgx-deb.key] https://download.01.org/intel-sgx/sgx_repo/ubuntu '${UBUNTU_CODENAME}' main' > /etc/apt/sources.list.d/intel-sgx.list

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y gramine \
    sgx-aesm-service \
    libsgx-aesm-launch-plugin \
    libsgx-aesm-epid-plugin \
    libsgx-aesm-quote-ex-plugin \
    libsgx-aesm-ecdsa-plugin \
    libsgx-dcap-quote-verify \
    psmisc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/run/aesmd/


# COPY /usr/local/lib/ /usr/local/lib/
#COPY runtimedir/libgcc_s.so.1 /lib/x86_64-linux-gnu/libgcc_s.so.1
#COPY runtimedir/libstdc++.so.6 /lib/x86_64-linux-gnu/libstdc++.so.6
#COPY runtimedir/libsodium.so.23 /lib/x86_64-linux-gnu/libsodium.so.23
#COPY runtimedir/libc.so.6 /lib/x86_64-linux-gnu/libc.so.6

COPY restart_aesm.sh /restart_aesm.sh

# Install additional tools
RUN apt update && apt install -y git make gcc wget libsgx-dcap-ql libsgx-quote-ex libsgx-dcap-default-qpl pkg-config vim
ENV SGX_AESM_ADDR=1
ENV MAC_KEY_SHARE_0_P="-88222337191559387830816715872691188861"
ENV MAC_KEY_SHARE_0_N="f0cf6099e629fd0bda2de3f9515ab72b"
ENV MAC_KEY_SHARE_1_P="1113507028231509545156335486838233835"
ENV MAC_KEY_SHARE_1_N="c347ce3d9e165e4e85221f9da7591d98"
ENV KII_TUPLES_PER_JOB="10000"
ENV KII_PLAYER_NUMBER="0"
ENV KII_PLAYER_COUNT="2"
ENV KII_TUPLE_TYPE="BIT_GFP"
ENV PRIME="198766463529478683931867765928436695041"
ENV KII_JOB_ID="123456"
ENV KII_TUPLE_FILE="/kii/tuples"

COPY azure_sgx_qcnl.conf /etc/sgx_default_qcnl.conf

# Copy resources
COPY 3RD-PARTY-LICENSES /3RD-PARTY-LICENSES
COPY kii-run.c .
COPY kii-run.manifest.template .
COPY Makefile .
COPY azure_sgx_qcnl.conf .
RUN cp libSPDZ.so /usr/local/lib/

RUN gramine-sgx-gen-private-key


# RUN make clean && make SGX=1

# Remove the Player-Data directory if it exists, recreate it, and set up subdirectories
RUN rm -rf Player-Data && \
    mkdir -p Player-Data/2-2-40 && \
    mkdir -p Player-Data/2-p-128

# Generate the Gramine manifest
#RUN gramine-manifest -Dlog_level=error file_2.manifest.template file_2.manifest


# Sign the manifest (if SGX mode is enabled)
#RUN gramine-sgx-sign --manifest file_2.manifest --output file_2.manifest.sgx

# Add information to 3rd party licenses
RUN printf "\n## Klyshko MP-SPDZ\n\
General information about third-party software components and their licenses, \
which are distributed with Klyshko MP-SPDZ, can be found in the \
[SBOM](./sbom.json). Further details are available in the subfolder for the \
respective component or can be downloaded from the \
[Klyshko Release Page](%s).\n" "${RELEASE_PAGE}"\
>> /3RD-PARTY-LICENSES/disclosure.md

# Run the Gramine-SGX or Gramine-Direct process based on the environment
CMD ["/bin/bash", "-c", "gramine-sgx kii-run"]